namespace: letshop

replicas: 2

images:
  backend:
    repository: 919651863390.dkr.ecr.ap-southeast-2.amazonaws.com/letshop-production-backend
    tag: latest
    pullPolicy: IfNotPresent
  frontend:
    repository: 919651863390.dkr.ecr.ap-southeast-2.amazonaws.com/letshop-production-frontend
    tag: latest
    pullPolicy: IfNotPresent

service:
  backend:
    port: 5000
    targetPort: 5000
    type: ClusterIP
  frontend:
    port: 80
    targetPort: 80
    type: LoadBalancer

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: letshop-backend
              port: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: letshop-frontend
              port: 80

config:
  PORT: "5000"
  VITE_API_URL: "http://letshop-backend:5000/api"

secrets:
  create: false
  DATABASE_URL: ""
  JWT_SECRET: ""
  ADMIN_EMAIL: ""
  ADMIN_PASSWORD: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_REGION: ""
  AWS_BUCKET_NAME: ""

resources:
  backend:
    requests:
      cpu: "128m"
      memory: "256Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  frontend:
    requests:
      cpu: "64m"
      memory: "128Mi"
    limits:
      cpu: "256m"
      memory: "256Mi"

probes:
  backend:
    liveness:
      path: /api/health
      port: 5000
      initialDelaySeconds: 15
      periodSeconds: 10
    readiness:
      path: /api/health
      port: 5000
      initialDelaySeconds: 5
      periodSeconds: 5
  frontend:
    liveness:
      path: /
      port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      path: /
      port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
