{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: letshop-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{- if and (ne $key "create") $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
