apiVersion: v1
kind: Service
metadata:
  name: letshop-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: letshop-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.targetPort }}
  type: {{ .Values.service.frontend.type }}
