aws_region              = "ap-southeast-2"
environment             = "dev"
app_name                = "letshop"
vpc_cidr                = "10.0.0.0/16"
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
ssh_key_name            = "/Users/admin/Downloads/my-Key"
admin_allowed_cidr_blocks = ["0.0.0.0/0"]
monitoring_allowed_cidr_blocks = ["0.0.0.0/0"]
monitoring_instance_type = "c7i-flex.large"
prometheus_enabled      = true
grafana_enabled         = true
grafana_admin_password  = ""
eks_enabled             = true
eks_version             = "1.30"
eks_node_instance_types = ["c7i-flex.large"]
eks_node_min_size       = 1
eks_node_desired_size   = 2
eks_node_max_size       = 3
